// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cart-pages/Mobile.tsx": () => import("../components/mockups/cart-pages/Mobile.tsx"),
  "./components/mockups/cart-pages/Premium.tsx": () => import("../components/mockups/cart-pages/Premium.tsx"),
  "./components/mockups/cart-pages/Trendyol.tsx": () => import("../components/mockups/cart-pages/Trendyol.tsx")
};
